# Generated by Django 4.1.9 on 2023-05-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_addres_alter_user_options_user_birth_date_user_cnpj_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("announces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announce",
            name="addres",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.addres"),
        ),
        migrations.AddField(
            model_name="announce",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="criador", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="announce",
            name="inscripts",
            field=models.ManyToManyField(related_name="inscripts", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="announce",
            name="tags",
            field=models.ManyToManyField(to="announces.tag"),
        ),
    ]
