# Generated by Django 4.1.9 on 2023-05-30 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("announces", "0002_announcement_address_announcement_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="address",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.address"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="course",
            field=models.CharField(
                choices=[
                    ("ALIMENTOS", "Alimentos"),
                    ("APICULTURA", "Apicultura"),
                    ("INFORMATICA", "Informatica"),
                    ("ADS", "Analise e desenvolvimento de sistemas"),
                    ("QUIMICA", "Quimica"),
                    ("AGROINDUSTRIA", "Agroindustria"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="criador", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
