# Generated by Django 4.1.9 on 2023-05-30 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("announces", "0003_alter_announcement_address_alter_announcement_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="inscripts",
            field=models.ManyToManyField(blank=True, related_name="inscripts", to=settings.AUTH_USER_MODEL),
        ),
    ]
