# Generated by Django 4.1.9 on 2023-07-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announces", "0008_alter_announcement_creation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="rate",
            field=models.FloatField(default=0),
        ),
    ]
