# Generated by Django 4.1.9 on 2023-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_address_cep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=14, null=True),
        ),
    ]
