# Generated by Django 4.1.9 on 2023-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="course",
            field=models.CharField(
                choices=[
                    ("ALIMENTOS", "Alimentos"),
                    ("APICULTURA", "Apicultura"),
                    ("INFORMATICA", "Informatica"),
                    ("ADS", "Tecnologia em Análise e Desenvolvimento de Sistemas"),
                    ("QUIMICA", "Quimica"),
                    ("AGROINDUSTRIA", "Agroindustria"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
