# Generated by Django 4.1.9 on 2023-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(default="user_base.jpg", upload_to="profile_pictures/"),
        ),
    ]
