# Generated by Django 4.1.9 on 2023-07-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="cep",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(blank=True, default="S/N", max_length=10),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="schooling",
            field=models.CharField(
                choices=[
                    ("NAO_ALFABETIZADO", "Não alfabetizado"),
                    ("EF_INCOMPLETO", "Ensino fundamental incompleto"),
                    ("EF_COMPLETO", "Ensino fundamental completo"),
                    ("CURSANDO_EF", "Cursando ensino fundamental"),
                    ("EM_INCOMPLETO", "Ensino médio incompleto"),
                    ("EM_COMPLETO", "Ensino médio completo"),
                    ("CURSANDO_EM", "Cursando ensino médio"),
                    ("ES_INCOMPLETO", "Ensino superior incompleto"),
                    ("ES_COMPLETO", "Ensino superior completo"),
                    ("CURSANDO_ES", "Cursando ensino superior"),
                    ("MESTRADO", "Mestrado"),
                    ("DOUTORADO", "Doutorado"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
